version: 0.1.{build}

environment:
  matrix:
    - nodejs_version: 8
      MINICONDA: C:\Miniconda36-x64

platform:
  - x64

#services:

cache:
  - node_modules -> package-lock.json
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

init:
  - git config --global core.autocrlf input
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"
  - conda install -y conda-build

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm i

build_script:
  - npm run pack
  - conda build recipe\
  - dir C:\Miniconda36-x64\conda-bld\win-64

after_build:
  - 7z a release.zip release/latest.yml release/*.exe
  - 7z a conda-win-64.zip C:\Miniconda36-x64\conda-bld\win-64\

artifacts:
  - path: release.zip
    name: release
  - path: conda-win-64.zip
    name: conda_package

test: off
